name: Release
on:
  push:
    tags:
      - 'v*'
  release:
    types:
      - edited

permissions:
  contents: write

jobs:
  handle-release:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'

    - run: npm install

    - run: xvfb-run -a npm test
      if: runner.os == 'Linux'

    - name: Generate coverage badge
      uses: jaywcjlove/coverage-badges-cli@main
      with:
        source: coverage/coverage-summary.json
        output: coverage/badge.svg

    - name: Convert SVG to PNG
      uses: joergnapp/convert-svg-to-png@v1.0
      with:
        svgpath: 'coverage/'
        pngpath: 'coverage/'

    - name: Push coverage badge
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./coverage
        destination_dir: coverage

    - name: Build
      run: npm run build

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: promptis-*.vsix
        fail_on_unmatched_files: true
